# (c) https://github.com/MontiCore/monticore

image: maven:3.5.4-jdk-11

stages:
  - build
  - deploy
  - check

before_script:
  - chmod +x gradlew
  - chmod +x check/downloadlinkchecker.sh
  - chmod +x check/mdlinkcheck.sh
  - export GRADLE_USER_HOME=`pwd`/.gradle


build:
  stage: build
  script:
    - "./gradlew build $GRADLE_OPT $ARGS1"
  artifacts:
    paths:
      - target/
    expire_in: 1 week
    
    
deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - "./gradlew publish -PmavenPassword=$pass -PmavenUser=$user $GRADLE_OPT $ARGS2"
  artifacts:
    paths:
      - target/libs/statecharts-cli.jar
    expire_in: 1 week
  only:
    refs:
      - dev

checkMDLinks:
  stage: check
  dependencies:
    - deploy
  script:
    - "./check/downloadlinkchecker.sh $secibuildtoken"
    - "url=https://git.rwth-aachen.de/monticore/statechart/sc-language/-/blob/dev/src/main/grammars/de/monticore/Statecharts.md"
    - "./check/mdlinkcheck.sh -url $url -t $secibuildtoken -p"
  only:
    - dev
